### ISSUE TITLE
issue for cl_to_corr.py

### ISSUE THREAD

**Issue by audita-nimas** [joezuntz/cosmosis-doc#1]
Hi Joe! 
I tried to modify 2pt in demo6/tutorial 5 with file shear/cl_to_corr/cl_to_corr.py, but I have an error: ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'. could you help me to solve this? thank you so much

**Comment by joezuntz** [comment]
Hi @audita-nimas - sorry to miss this earlier, this is the github for the cosmosis documentation; I don't usually use it for science questions.  I'll close it after these conversations.

I can see the problem you have found, and have a fix that I am testing here:
https://github.com/joezuntz/cosmosis-standard-library/pull/35

If it works I will merge it.

**Comment by audita-nimas** [comment]
Hi Joe, thank you so much. I have changed and rerun again. but I found this one again:
(Could not get a likelihood) Error:3: Could not find section called  (name was nbin)
(There was an error so no output to save)

I think your cl_to corr okay now but when I calculate the likelihood I got the problem. isn't it?

**Comment by joezuntz** [comment]
Hi @audita-nimas - could you be more specific about what pipeline you are running, e.g. sharing the parameter file you have used?

**Comment by joezuntz** [comment]
And also if you run the test sampler with the setting fatal_errors=T in the `[test]` section it will give more info.

**Comment by audita-nimas** [comment]
Hi Joe, the pipeline that I used are consistency camb sigma8_rescale load_nz angular_power bin_bias gamma_t 2pt_like with parameter that randon are just bin_bias. I wrote:

[gamma_t]
file = shear/cl_to_corr/cl_to_corr.py
corr_type = gamma

and 

[2pt_like]
file = likelihood/2pt/2pt_like.py
data_file = /Users/nemas/Documents/PhD/task_3_cosmosis/newfits/gt_output_kids.fits
data_sets = gammat
make_covariance=F
covmat_name=COVMAT

the completed error that I got:
Traceback (most recent call last):
  File "/Users/nemas/cosmosis-trial5/env/bin/cosmosis", line 4, in <module>
    status = cosmosis.main.main()
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/main.py", line 389, in main
    return run_cosmosis(args)
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/main.py", line 292, in run_cosmosis
    sampler_main_loop(sampler, output, pool, is_root)
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/main.py", line 74, in sampler_main_loop
    sampler.execute()
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/samplers/test/test_sampler.py", line 31, in execute
    like, extra, data = self.pipeline.likelihood(p, return_data=True)
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/runtime/pipeline.py", line 1344, in likelihood
    data = self.run_parameters(p, all_params=all_params)
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/runtime/pipeline.py", line 1110, in run_parameters
    if self.run(data):
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/runtime/pipeline.py", line 631, in run
    status = module.execute(data_package)
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/runtime/module.py", line 249, in execute
    return self.execute_function(data_block, self.data)
  File "/Users/nemas/cosmosis-trial5/cosmosis-standard-library/shear/cl_to_corr/cl_to_corr.py", line 295, in execute
    transformer(block)
  File "/Users/nemas/cosmosis-trial5/cosmosis-standard-library/shear/cl_to_corr/cl_to_corr.py", line 219, in __call__
    nbin_a = nbin_b = block[self.input_section, "nbin"]
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/datablock/cosmosis_py/block.py", line 852, in __getitem__
    return self.get(section, name)
  File "/Users/nemas/cosmosis-trial5/env/lib/python3.9/site-packages/cosmosis/datablock/cosmosis_py/block.py", line 674, in get
    raise BlockError.exception_for_status(status, section, name)
cosmosis.datablock.cosmosis_py.errors.BlockSectionNotFound: 3: Could not find section called  (name was nbin)

**Comment by joezuntz** [comment]
Hi @audita-nimas  - so this module is looking at the output of the angular_power module, and it's not finding what it needs.  Usually that means that the parameter names don't quite match - could you send the whole parameter ini file and we can have a look?  You might just need to set the parameter `input_section_name`.

**Comment by audita-nimas** [comment]
Hi Joe, here my whole parameter ini file:

[cosmological_parameters]
omega_m = 0.286 
h0 = 0.7
omega_b = 0.046
tau = 0.08
n_s = 0.96
A_s = 2.1e-9
sigma8_input = 0.82

[bin_bias]
b1 =  0.000001 1.26 5
b2 = 0.000001 1.47 5
b3 = 0.000001 2.04 5
b4 = 0.000001 2.09 5


is there any wrong that I did?

**Comment by joezuntz** [comment]
Hi @audita-nimas - I meant the complete content of the other parameter file, the main one that you run cosmosis on.
(In my poorly chosen cosmosis language the "parameter" file is the main one, like e.g. demo6.ini, and the one with the cosmological values in is the "values" file, like values6.ini.

**Comment by audita-nimas** [comment]
Hi Joe, I see. here we go:


[runtime]
sampler = test

[test]
save_dir = output/output_gammat2
fatal_errors=T

[output]
format=text
filename=output/output_gammat_emcee2.txt

[emcee]
walkers = 32
samples = 4000
nsteps = 1000

[pipeline]
modules = consistency camb sigma8_rescale load_nz angular_power bin_bias gamma_t 2pt_like
values = phd/values_gammat.ini

[consistency]
file = ./utility/consistency/consistency_interface.py

[camb]
file = boltzmann/camb/camb_interface.py
mode = all
lmax = 2500
nz_background = 201
zmax_background = 2.
feedback = 0
halofit_version = takahashi

[sigma8_rescale]
file = utility/sample_sigma8/sigma8_rescale.py

[load_nz]
file = number_density/load_nz_fits/load_nz_fits.py
nz_file = /Users/nemas/Documents/PhD/task_3_cosmosis/newfits/gt_output_kids.fits
data_sets = lens source

[unbiased_galaxies] 
file = ./bias/no_bias/no_bias.py

[angular_power]
file = structure/projection/project_2d.py
ell_min_logspaced = 1.0
ell_max_logspaced = 100000.0
n_ell_logspaced = 500
position-shear = lens-source
verbose = T

[bin_bias]
file = bias/binwise_bias/bin_bias.py
perbin = T

[gamma_t]
file = shear/cl_to_xi_wigner/wigner_cl_xi_interface.py
corr_type = 2/gammat

[2pt_like]
file = likelihood/2pt/2pt_like.py
;include_norm=T
data_file = /Users/nemas/Documents/PhD/task_3_cosmosis/newfits/gt_output_kids.fits
data_sets = gammat
make_covariance=F
covmat_name=COVMAT

**Comment by joezuntz** [comment]
Hi Audita - thanks.

This is a bit strange because your pipeline works for me using a different fits file, at least as far as cl_to_corr which is where we have the error you are seeing. 

It's possible you still have the old version of the code before my recent fix - could you try doing 
`git pull` in the cosmosis-standard-library directory and then re-running?  And if that doesn't work post the output of `git show --oneline -s` here?

**Comment by audita-nimas** [comment]
Hi Joe, 

I have already done with git pull and still got the same error: raise BlockError.exception_for_status(status, section, name)
cosmosis.datablock.cosmosis_py.errors.BlockSectionNotFound: 3: Could not find section called  (name was nbin)

I tried use the data from your examples but still get same trouble.

**Comment by audita-nimas** [comment]
Hi Joe, after I installed again, I can run the script and got the result. thank you so much, Joe!

if I have any problem again, where should I report my problem?

**Comment by joezuntz** [comment]
That's great, glad to hear it! 

The best place to report questions is here: https://github.com/joezuntz/cosmosis/issues

Should we also close your other issue here, this one: https://github.com/joezuntz/cosmosis-doc/issues/2
?

**Comment by audita-nimas** [comment]
yes, we can close the issue for that.

**Comment by joezuntz** [comment]
Thanks!
