### ISSUE TITLE
defining H(z) in class interface

### ISSUE THREAD

**Issue by asmaamaz** [joezuntz/cosmosis-doc#4]
Hi,
I need to use the bossdr12 likelihood for BAO which needs to have 'h' in section distances which at the moment isn't defined in the class interface. I have already tried multiple ways of defining this quantity  but unfortunately nothing has worked. 
I would really appreciate your help.

**Comment by joezuntz** [comment]
Hi there ,

Thanks for spotting this omission. I'm testing a fix for it now, here, along with something requested by another user:
https://github.com/joezuntz/cosmosis-standard-library/pull/50

If the tests all pass I will merge the fix into the main branch so you should be able to pull it easily.

(Incidenally, please use this page for cosmosis issues: https://github.com/joezuntz/cosmosis/issues - tThe current page is for the documentation.)

**Comment by joezuntz** [comment]
This is fixed now - the class module outputs H(z) in the same units as camb, so it should work for BAO. Do let me know if not though.

You can get the new version with the command `git pull` in your cosmosis-standard-library directory.

Cheers,
Joe

**Comment by joezuntz** [comment]
(Also I've just found out I can transfer this issue to the other repo, so I'll do that for posterity)
